version: '3'
services:
  mysql:
    build: .
    image: my/mysql5.7
    container_name: 'mysql'
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
